import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { DatabaseSync, type SQLInputValue } from "node:sqlite";
import test from "node:test";
import type { ClassroomD1 } from "../db";
import type { AuthenticatedClassroomUser } from "../app/lib/classroom-api";
import { ClassroomError } from "../app/lib/classroom-errors";
import { closeManagedHomeworkAssignment, createManagedHomeworkTemplate, getManagedHomeworkConsole, getOwnHomeworkAssignment, listOwnHomeworkAssignments, publishManagedHomeworkAssignment, saveManagedHomeworkFeedback, saveOwnHomeworkResponse, updateManagedHomeworkTemplate } from "../app/lib/managed-homework-store";

type LocalStatement=D1PreparedStatement&{execute():D1Result}; type LocalDatabase=ClassroomD1&{raw:DatabaseSync};
function database():LocalDatabase{const raw=new DatabaseSync(":memory:");raw.exec("PRAGMA foreign_keys = ON");for(const name of readdirSync(new URL("../drizzle/",import.meta.url)).filter(n=>/^\d{4}_.*\.sql$/.test(n)).sort())raw.exec(readFileSync(new URL(`../drizzle/${name}`,import.meta.url),"utf8"));const api={raw,prepare(sql:string){let values:SQLInputValue[]=[];const statement={bind(...input:unknown[]){values=input as SQLInputValue[];return statement},async first<T>(){return(raw.prepare(sql).get(...values) as T|undefined)??null},async all<T>(){return{results:raw.prepare(sql).all(...values) as T[]}},async run(){return statement.execute()},execute(){const result=raw.prepare(sql).run(...values);return{success:true,meta:{changes:result.changes}} as unknown as D1Result}};return statement},async batch(statements:LocalStatement[]){raw.exec("BEGIN IMMEDIATE");try{const out=statements.map(s=>s.execute());raw.exec("COMMIT");return out}catch(e){raw.exec("ROLLBACK");throw e}}};return api as unknown as LocalDatabase}
function actor(id:string,role:"admin"|"mentor"|"learner"):AuthenticatedClassroomUser{return{userId:id,username:id,displayName:id,platformRole:role,actorProfileId:id,effectiveProfileId:id,impersonationId:null}}
function seed(db:LocalDatabase){const now="2026-09-15T00:00:00.000Z";for(const[id,role]of[["admin","admin"],["mentor","mentor"],["outsider-mentor","mentor"],["learner-a","learner"],["learner-b","learner"],["learner-c","learner"]]as const){db.raw.prepare("INSERT INTO auth_users (id,username,display_name,role,status,password_hash,password_salt,password_iterations,password_changed_at,must_change_password,created_at,updated_at) VALUES (?,?,?,?,'active','h','s',1,?,0,?,?)").run(id,id,id,role,now,now,now);db.raw.prepare("INSERT INTO profiles (id,nickname,created_at,updated_at) VALUES (?,?,?,?)").run(id,id,now,now)}db.raw.prepare("INSERT INTO course_versions (course_id,revision,schema_version,digest,package_json,created_at,created_by) VALUES ('c',1,1,'d','{}',?,'admin')").run(now);db.raw.prepare("INSERT INTO rooms (id,code,title,campaign_id,chapter_id,phase,status,dm_profile_id,version,paused,player_timeline_frozen,history_revealed,created_at,updated_at) VALUES ('room','ROOM','七年级创意队','x','B01','lobby','active','mentor',1,0,0,0,?,?)").run(now,now);db.raw.prepare("INSERT INTO classroom_instances (room_id,environment,learner_count,lifecycle,state_machine_version,course_id,course_revision,course_digest,factory_key,reset_generation,created_at,updated_at) VALUES ('room','test',2,'ready',1,'c',1,'d','f',0,?,?)").run(now,now);for(const[id,profile,role,seat]of[["m0","mentor","dm",null],["m1","learner-a","learner",1],["m2","learner-b","learner",2]]as const)db.raw.prepare("INSERT INTO memberships (id,room_id,profile_id,role,seat,status,last_seen_at,created_at,updated_at) VALUES (?,'room',?,?,?,'active',?,?,?)").run(id,profile,role,seat,now,now,now)}
const fields=[{id:"idea",label:"一句话创意",kind:"long",required:true},{id:"mode",label:"玩法",kind:"single",required:false,options:["探索","建造"]}] as const;

test("T-125 versions templates, freezes recipients and exact fields at delivery",async()=>{const db=database();seed(db);try{const mentor=actor("mentor","mentor");const created=await createManagedHomeworkTemplate(db,mentor,{title:"创意周报",description:"每周复用",fields,requestKey:"template.create.001"});assert.equal(created.revision,1);const replay=await createManagedHomeworkTemplate(db,mentor,{title:"创意周报",description:"每周复用",fields,requestKey:"template.create.001"});assert.equal(replay.id,created.id);const sent=await publishManagedHomeworkAssignment(db,mentor,{templateId:created.id,roomId:"room",title:"第一周",instructions:"写具体",requestKey:"assignment.send.001"});assert.equal(sent.recipientCount,2);db.raw.prepare("INSERT INTO memberships (id,room_id,profile_id,role,seat,status,last_seen_at,created_at,updated_at) VALUES ('m3','room','learner-c','learner',3,'active',?,?,?)").run("2026","2026","2026");const next=await updateManagedHomeworkTemplate(db,mentor,created.id,{expectedRevision:1,title:"创意周报",description:"新版",fields:[{id:"new",label:"新问题",kind:"short",required:true}]});assert.equal(next.revision,2);const consoleData=await getManagedHomeworkConsole(db,mentor);assert.deepEqual(consoleData.assignments[0].fields.map(f=>f.id),["idea","mode"]);assert.deepEqual(consoleData.assignments[0].responses.map(r=>r.profileId).sort(),["learner-a","learner-b"]);assert.equal((await listOwnHomeworkAssignments(db,actor("learner-c","learner"))).length,0)}finally{db.raw.close()}});

test("T-125 enforces learner/staff scope, required answers, feedback and closure",async()=>{const db=database();seed(db);try{const mentor=actor("mentor","mentor"),learner=actor("learner-a","learner");const template=await createManagedHomeworkTemplate(db,mentor,{title:"行动卡",fields,requestKey:"template.create.002"});const sent=await publishManagedHomeworkAssignment(db,mentor,{templateId:template.id,roomId:"room",requestKey:"assignment.send.002"});await assert.rejects(getOwnHomeworkAssignment(db,actor("learner-c","learner"),sent.id),(e:unknown)=>e instanceof ClassroomError&&e.code==="HOMEWORK_ASSIGNMENT_NOT_FOUND");await saveOwnHomeworkResponse(db,learner,sent.id,{status:"draft",answers:{}});await assert.rejects(saveOwnHomeworkResponse(db,learner,sent.id,{status:"submitted",answers:{}}),(e:unknown)=>e instanceof ClassroomError&&e.code==="HOMEWORK_REQUIRED_MISSING");const submitted=await saveOwnHomeworkResponse(db,learner,sent.id,{status:"submitted",answers:{idea:"做一个提醒器",mode:["探索"]}});assert.equal(submitted.response?.status,"submitted");await assert.rejects(saveManagedHomeworkFeedback(db,actor("outsider-mentor","mentor"),sent.id,"learner-a",{feedback:"越权"}),(e:unknown)=>e instanceof ClassroomError&&e.code==="HOMEWORK_CLASSROOM_FORBIDDEN");const reviewed=await saveManagedHomeworkFeedback(db,mentor,sent.id,"learner-a",{feedback:"把使用者写得再具体一点"});assert.equal(reviewed.responses.find(r=>r.profileId==="learner-a")?.feedback,"把使用者写得再具体一点");await closeManagedHomeworkAssignment(db,mentor,sent.id);await assert.rejects(saveOwnHomeworkResponse(db,learner,sent.id,{status:"draft",answers:{idea:"改写"}}),(e:unknown)=>e instanceof ClassroomError&&e.code==="HOMEWORK_ASSIGNMENT_CLOSED")}finally{db.raw.close()}});

test("T-125 blocks non-owner template edits while allowing admin override",async()=>{const db=database();seed(db);try{const created=await createManagedHomeworkTemplate(db,actor("mentor","mentor"),{title:"权限模板",fields,requestKey:"template.create.003"});await assert.rejects(updateManagedHomeworkTemplate(db,actor("outsider-mentor","mentor"),created.id,{expectedRevision:1,title:"越权",fields}),(e:unknown)=>e instanceof ClassroomError&&e.code==="HOMEWORK_TEMPLATE_EDIT_FORBIDDEN");const adminEdit=await updateManagedHomeworkTemplate(db,actor("admin","admin"),created.id,{expectedRevision:1,title:"管理员纠正",fields});assert.equal(adminEdit.revision,2)}finally{db.raw.close()}});

test("T-125 idempotency keys replay identical writes and reject altered payloads",async()=>{const db=database();seed(db);try{const mentor=actor("mentor","mentor");const template=await createManagedHomeworkTemplate(db,mentor,{title:"幂等模板",fields,requestKey:"template.create.004"});await assert.rejects(createManagedHomeworkTemplate(db,mentor,{title:"同键不同模板",fields,requestKey:"template.create.004"}),(e:unknown)=>e instanceof ClassroomError&&e.code==="HOMEWORK_REQUEST_CONFLICT");await publishManagedHomeworkAssignment(db,mentor,{templateId:template.id,roomId:"room",title:"第一次",requestKey:"assignment.send.004"});await assert.rejects(publishManagedHomeworkAssignment(db,mentor,{templateId:template.id,roomId:"room",title:"同键另一标题",requestKey:"assignment.send.004"}),(e:unknown)=>e instanceof ClassroomError&&e.code==="HOMEWORK_REQUEST_CONFLICT")}finally{db.raw.close()}});
