"use client";
import { type FormEvent, useCallback, useEffect, useRef, useState } from "react";
import styles from "./homework.module.css";

type Field = { id: string; label: string; kind: "short"|"long"|"single"|"multi"; required: boolean; options?: string[] };
type Template = { id: string; title: string; description: string; revision: number; status: string; fields: Field[]; createdByProfileId: string; createdByName: string; updatedAt: string };
type ResponseRow = { profileId: string; username: string; displayName: string; responseId: string|null; status: string; answers: Record<string,string|string[]>; submittedAt: string|null; feedback: string; feedbackAt: string|null };
type Assignment = { id: string; templateId: string; templateRevision: number; roomId: string; roomTitle: string; title: string; instructions: string; status: "published"|"closed"; recipientCount: number; dueAt: string|null; publishedAt: string; fields: Field[]; responses: ResponseRow[] };
type ConsoleData = { templates: Template[]; rooms: Array<{ id:string; title:string; environment:"test"|"production"; learnerCount:number }>; assignments: Assignment[] };
type Envelope<T>={ok:boolean;data?:T;error?:{message?:string}};
const emptyField=():Field=>({id:`q${Math.random().toString(36).slice(2,8)}`,label:"",kind:"long",required:false});

export default function ManagedHomeworkClient({userId,role}:{userId:string;role:string}){
 const [data,setData]=useState<ConsoleData|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState("");
 const [selectedTemplate,setSelectedTemplate]=useState(""),[selectedAssignment,setSelectedAssignment]=useState("");
 const [draft,setDraft]=useState({id:"",revision:0,title:"",description:"",fields:[emptyField()]});
 const templateKey=useRef(`template.${crypto.randomUUID()}`), assignmentKey=useRef(`assignment.${crypto.randomUUID()}`);
 const templateRef=useRef(""),assignmentRef=useRef("");
 const load=useCallback(async()=>{try{const next=await api<ConsoleData>("/api/homework/assignments");setData(next);setError("");const templateId=templateRef.current&&next.templates.some(t=>t.id===templateRef.current)?templateRef.current:next.templates[0]?.id??"";const assignmentId=assignmentRef.current&&next.assignments.some(a=>a.id===assignmentRef.current)?assignmentRef.current:next.assignments[0]?.id??"";templateRef.current=templateId;assignmentRef.current=assignmentId;setSelectedTemplate(templateId);setSelectedAssignment(assignmentId);const picked=next.templates.find(t=>t.id===templateId);if(picked)setDraft(templateDraft(picked));}catch(e){setError(message(e));}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[load]);
 const template=data?.templates.find(t=>t.id===selectedTemplate), assignment=data?.assignments.find(a=>a.id===selectedAssignment);
 function selectTemplate(id:string){templateRef.current=id;setSelectedTemplate(id);const picked=data?.templates.find(t=>t.id===id);if(picked)setDraft(templateDraft(picked))}
 function selectAssignment(id:string){assignmentRef.current=id;setSelectedAssignment(id)}
 function newTemplate(){templateRef.current="";setSelectedTemplate("");setDraft({id:"",revision:0,title:"",description:"",fields:[emptyField()]});templateKey.current=`template.${crypto.randomUUID()}`}
 function updateField(index:number,patch:Partial<Field>){setDraft(v=>({...v,fields:v.fields.map((f,i)=>i===index?{...f,...patch}:f)}))}
 async function saveTemplate(event:FormEvent){event.preventDefault();setBusy("template");setNotice("");try{const payload={title:draft.title,description:draft.description,fields:draft.fields.map(f=>({...f,options:f.kind==="single"||f.kind==="multi"?(f.options??[]).filter(Boolean):undefined}))};const saved=draft.id?await api<Template>(`/api/homework/templates/${draft.id}`,{method:"PATCH",body:{...payload,expectedRevision:draft.revision}}):await api<Template>("/api/homework/templates",{method:"POST",body:{...payload,requestKey:templateKey.current}});setNotice(`模板“${saved.title}”r${saved.revision} 已保存。旧发放仍保留原版本。`);templateKey.current=`template.${crypto.randomUUID()}`;templateRef.current=saved.id;await load()}catch(e){setError(message(e))}finally{setBusy("")}}
 async function publish(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!template||!data)return;const form=event.currentTarget;const fd=new FormData(form),room=data.rooms.find(r=>r.id===fd.get("roomId"));if(!room)return;const title=String(fd.get("title")??"").trim()||template.title;if(!confirm(`确认把“${title}”发给：\n${room.environment.toUpperCase()} · ${room.title}\n当前 ${room.learnerCount} 名学员\n\n发送后收件名单与模板 r${template.revision} 固定，后续改模板或课堂成员不会悄悄改变本次作业。`))return;setBusy("assignment");try{const saved=await api<Assignment>("/api/homework/assignments",{method:"POST",body:{templateId:template.id,roomId:room.id,title,instructions:String(fd.get("instructions")??""),dueAt:String(fd.get("dueAt")??""),requestKey:assignmentKey.current}});assignmentKey.current=`assignment.${crypto.randomUUID()}`;assignmentRef.current=saved.id;setNotice(`已发给 ${saved.recipientCount} 名学员。`);await load();form.reset()}catch(e){setError(message(e))}finally{setBusy("")}}
 async function close(){if(!assignment||!confirm(`确认截止“${assignment.title}”？学员之后只能查看，不能再修改答案。`))return;setBusy("close");try{await api(`/api/homework/assignments/${assignment.id}`,{method:"PATCH",body:{action:"close"}});setNotice("作业已截止，已有答案和反馈完整保留。");await load()}catch(e){setError(message(e))}finally{setBusy("")}}
 async function feedback(row:ResponseRow,value:string){if(!assignment)return;setBusy(`feedback:${row.profileId}`);try{await api(`/api/homework/assignments/${assignment.id}/feedback/${row.profileId}`,{method:"PATCH",body:{feedback:value}});setNotice(`已保存给 ${row.displayName} 的反馈。`);await load()}catch(e){setError(message(e))}finally{setBusy("")}}
 const canEdit=!draft.id||role==="admin"||template?.createdByProfileId===userId;
 return <div className={styles.page}>
  <header className={styles.hero}><div><small>AFTER-CLASS · CONTROLLED DELIVERY</small><h1>课后作业</h1><p>模板、课堂收件人、学员答案彼此解耦。发放时锁定模板版本和当时的学员名单。</p></div><span>{data?`${data.templates.length} 模板 · ${data.assignments.length} 次发放`:"正在读取…"}</span></header>
  {error&&<div className={styles.error} role="alert">{error}<button onClick={()=>{setError("");void load()}}>重新读取</button></div>}{notice&&<div className={styles.notice} role="status">{notice}</div>}
  <nav className={styles.tabs}><a href="#templates">01 模板工坊</a><a href="#delivery">02 定向发放</a><a href="#results">03 回收反馈</a></nav>
  <section className={styles.workbench} id="templates"><aside><header><small>TEMPLATE LIBRARY</small><h2>可复用模板</h2><button type="button" onClick={newTemplate}>＋ 新模板</button></header>{data?.templates.map(t=><button type="button" key={t.id} data-active={draft.id===t.id} onClick={()=>selectTemplate(t.id)}><b>{t.title}</b><span>r{t.revision} · {t.createdByName}</span></button>)}</aside>
   <form className={styles.editor} onSubmit={saveTemplate}><header><div><small>{draft.id?`REVISION r${draft.revision}`:"NEW TEMPLATE"}</small><h2>{draft.id?"编辑后生成新版本":"创建作业模板"}</h2></div>{!canEdit&&<b>只读：仅创建者或管理员可修改</b>}</header><label>模板名称<input value={draft.title} maxLength={80} required disabled={!canEdit} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>给导师看的模板说明<textarea value={draft.description} maxLength={500} disabled={!canEdit} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className={styles.fields}>{draft.fields.map((f,i)=><fieldset key={`${f.id}-${i}`}><legend>题目 {i+1}</legend><label>题目文字<input value={f.label} maxLength={160} required disabled={!canEdit} onChange={e=>updateField(i,{label:e.target.value})}/></label><div><label>题型<select value={f.kind} disabled={!canEdit} onChange={e=>updateField(i,{kind:e.target.value as Field["kind"],options:["选项 1","选项 2"]})}><option value="short">短回答</option><option value="long">长回答</option><option value="single">单选</option><option value="multi">多选</option></select></label><label className={styles.check}><input type="checkbox" checked={f.required} disabled={!canEdit} onChange={e=>updateField(i,{required:e.target.checked})}/> 必填</label></div>{(f.kind==="single"||f.kind==="multi")&&<label>选项（每行一个）<textarea value={(f.options??[]).join("\n")} disabled={!canEdit} onChange={e=>updateField(i,{options:e.target.value.split("\n")})}/></label>}<button type="button" disabled={!canEdit||draft.fields.length===1} onClick={()=>setDraft(v=>({...v,fields:v.fields.filter((_,x)=>x!==i)}))}>删除此题</button></fieldset>)}</div><footer><button type="button" disabled={!canEdit||draft.fields.length>=30} onClick={()=>setDraft(v=>({...v,fields:[...v.fields,emptyField()]}))}>＋ 添加题目</button><button type="submit" disabled={!canEdit||busy==="template"}>{busy==="template"?"正在保存…":draft.id?"保存为下一版本":"创建模板"}</button></footer></form>
  </section>
  <section className={styles.delivery} id="delivery"><header><small>SNAPSHOT & SEND</small><h2>发给一场课堂</h2><p>这里的“团队”使用真实 Classroom 作为边界；发送前显示当前收件人数，发送后名单固定。</p></header><form onSubmit={publish}><label>使用模板<select value={selectedTemplate} onChange={e=>selectTemplate(e.target.value)} required><option value="">选择模板</option>{data?.templates.filter(t=>t.status==="active").map(t=><option key={t.id} value={t.id}>{t.title} · r{t.revision}</option>)}</select></label><label>目标课堂<select name="roomId" required><option value="">选择课堂</option>{data?.rooms.map(r=><option key={r.id} value={r.id}>{r.environment.toUpperCase()} · {r.title} · {r.learnerCount} 学员</option>)}</select></label><label>本次标题<input name="title" maxLength={100} placeholder={template?.title??"先选择模板"}/></label><label>发放说明<textarea name="instructions" maxLength={800} placeholder="学员打开时会看到这段具体说明"/></label><label>截止时间（可选）<input name="dueAt" type="datetime-local"/></label><button type="submit" disabled={!template||!data?.rooms.length||busy==="assignment"}>{busy==="assignment"?"正在锁定并发放…":"检查收件人并发放"}</button></form></section>
  <section className={styles.results} id="results"><header><div><small>RESPONSES & FEEDBACK</small><h2>回收与反馈</h2></div><select value={selectedAssignment} onChange={e=>selectAssignment(e.target.value)}><option value="">选择一次发放</option>{data?.assignments.map(a=><option key={a.id} value={a.id}>{a.roomTitle} · {a.title} · r{a.templateRevision}</option>)}</select></header>{assignment?<><div className={styles.assignmentMeta}><b>{assignment.title}</b><span>{assignment.roomTitle}</span><span>模板 r{assignment.templateRevision}</span><span>{assignment.responses.filter(r=>r.status==="submitted").length}/{assignment.recipientCount} 已提交</span><span>{assignment.status==="closed"?"已截止":"收集中"}</span>{assignment.status!=="closed"&&<button type="button" onClick={()=>void close()} disabled={busy==="close"}>截止作业</button>}</div><div className={styles.responseGrid}>{assignment.responses.map(row=><details key={row.profileId} className={styles.response}><summary><div><b>{row.displayName}</b><small>@{row.username}</small></div><span data-status={row.status}>{statusName(row.status)}</span></summary><div>{row.responseId?<>{assignment.fields.map(field=><article key={field.id}><b>{field.label}</b><p>{answerText(row.answers[field.id])||"（未填写）"}</p></article>)}<Feedback key={`${row.profileId}:${row.feedbackAt??"none"}`} row={row} busy={busy===`feedback:${row.profileId}`} onSave={value=>feedback(row,value)}/></>:<p>这名学员尚未开始填写。</p>}</div></details>)}</div></>:<div className={styles.empty}>发放作业后，这里会显示固定收件名单、完成状态、答案和反馈入口。</div>}</section>
 </div>
}
function Feedback({row,busy,onSave}:{row:ResponseRow;busy:boolean;onSave:(value:string)=>void}){const[value,setValue]=useState(row.feedback);return <form className={styles.feedback} onSubmit={e=>{e.preventDefault();void onSave(value)}}><label>导师反馈<textarea value={value} maxLength={1200} onChange={e=>setValue(e.target.value)}/></label><button disabled={busy}>{busy?"保存中…":"保存反馈"}</button></form>}
function templateDraft(template:Template){return{id:template.id,revision:template.revision,title:template.title,description:template.description,fields:template.fields.map(field=>({...field,options:field.options?[...field.options]:undefined}))}}
function statusName(s:string){return s==="submitted"?"已提交":s==="draft"?"草稿":"未开始"} function answerText(v?:string|string[]){return Array.isArray(v)?v.join("、"):v??""}
async function api<T>(path:string,opt:{method?:string;body?:unknown}={}){const r=await fetch(path,{method:opt.method??"GET",headers:{Accept:"application/json",...(opt.body?{"Content-Type":"application/json"}:{})},body:opt.body?JSON.stringify(opt.body):undefined,credentials:"same-origin"});const e=await r.json().catch(()=>null) as Envelope<T>|null;if(!r.ok||!e?.ok||e.data===undefined)throw new Error(e?.error?.message??"作业系统没有完成这次操作。");return e.data} function message(e:unknown){return e instanceof Error?e.message:"作业系统暂时没有响应。"}
